include:
  - component: gitlab.com/vaz-projects/gitlab/sane-workflow@${CI_COMMIT_SHA}
  - component: gitlab.com/vaz-projects/gitlab/stages@${CI_COMMIT_SHA}
  - component: gitlab.com/vaz-projects/gitlab/docker-image@${CI_COMMIT_SHA}
  - component: gitlab.com/vaz-projects/gitlab/release@${CI_COMMIT_SHA}
    inputs:
        changelogFile: changelog.md



Docker Image:
    rules:
      - changes:
          - Dockerfile
          - scripts/parse-changelog.fish
          - compose.yaml