include:
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/stages@${CI_COMMIT_SHA}
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/docker-image@${CI_COMMIT_SHA}
  - component: ${CI_SERVER_HOST}/${CI_PROJECT_PATH}/release@${CI_COMMIT_SHA}
    inputs:
        changelogFile: changelog.md



Docker Image:
    rules:
      - changes:
          - dockerfile
          - scripts/parse-changelog.fish
          - compose.yaml