services:
    builder:
        image: ${CI_REGISTRY_IMAGE:-vaz-projects/gitlab}/builder:latest
        
        build:
            context: .
            tags:
              - ${CI_REGISTRY_IMAGE:-vaz-projects/gitlab}/builder:${CI_COMMIT_REF_SLUG:-development}
            
            cache_from:
              - type=local,src=.staging/cache/buildkit/
            cache_to:
              - type=local,mode=max,compression=zstd,dest=.staging/cache/buildkit/