stages:
  - !reference [ .preBuildStage,        stage ]
  - !reference [ .buildStage,           stage ]
  - !reference [ .testStage,            stage ]
  - !reference [ .stagingPlanStage,     stage ]
  - !reference [ .stagingDeployStage,   stage ]
  - !reference [ .stagingTestStage,     stage ]
  - !reference [ .stagingCleanupStage,  stage ]
  - !reference [ .planStage,            stage ]
  - !reference [ .deployStage,          stage ]
  - !reference [ .releaseStage,         stage ]



# 
# Templates.
#-------------------------------------------------------------------------------
.baseStage:
    script:
      - echo "Running job '${CI_JOB_NAME}' with an empty script."


.rules:
    onMergeRequests:
        if: $CI_PIPELINE_TYPE == 'merge_request'
    
    onTags:
        if: $CI_PIPELINE_TYPE == 'tag'



# 
# Stages.
#-------------------------------------------------------------------------------
.preBuildStage:
    stage: 🛠️ Pre-Build
    
    extends: .baseStage
    
    interruptible: true


.buildStage:
    stage: 🏗️ Build
    
    extends: .baseStage
    
    interruptible: true


.testStage:
    stage: 🧪 Test
    
    extends: .baseStage
    
    interruptible: true


.stagingPlanStage:
    stage: 🚧 📋 Staging Plan
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.stagingDeployStage:
    stage: 🚧 🚀 Staging Deploy
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.stagingTestStage:
    stage: 🚧 🧪 Staging Test
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.stagingCleanupStage:
    stage: 🚧 🗑️ Staging Clean Up
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.planStage:
    stage: 📋 Plan
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onTags ]


.deployStage:
    stage: 🚀 Deploy
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onTags ]


.releaseStage:
    stage: 📦 Release
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onTags ]