stages:
  - !reference [ .preBuildStage, stage ]
  - !reference [ .buildStage, stage ]
  - !reference [ .testStage, stage ]
  - !reference [ .stagingStage, stage ]
  - !reference [ .testStagingStage, stage ]
  - !reference [ .cleanupStage, stage ]
  - !reference [ .deployStage, stage ]
  - !reference [ .releaseStage, stage ]



# 
# Templates.
#-------------------------------------------------------------------------------
.baseStage:
    script:
      - echo "Running job '${CI_JOB_NAME}' with an empty script."


.rules:
    onMergeRequests:
        if: $CI_PIPELINE_TYPE == 'merge_request'
    
    onTags:
        if: $CI_PIPELINE_TYPE == 'tag'



# 
# Stages.
#-------------------------------------------------------------------------------
.preBuildStage:
    stage: 🛠️ Pre Build
    
    extends: .baseStage
    
    interruptible: true


.buildStage:
    stage: 🛠️ Build
    
    extends: .baseStage
    
    interruptible: true


.testStage:
    stage: 🧪 Test
    
    extends: .baseStage
    
    interruptible: true


.stagingStage:
    stage: 🏗️ Staging
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.testStagingStage:
    stage: 🧪🏗️ Test Staging
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.cleanupStage:
    stage: 🗑️ Clean Up
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onMergeRequests ]


.deployStage:
    stage: 🚀 Deploy
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onTags ]


.releaseStage:
    stage: 📦 Release
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, onTags ]