stages:
  - !reference [ .buildStage, stage ]
  - !reference [ .testStage, stage ]
  - !reference [ .stagingStage, stage ]
  - !reference [ .testStagingStage, stage ]
  - !reference [ .cleanupStage, stage ]
  - !reference [ .deployStage, stage ]
  - !reference [ .releaseStage, stage ]



# 
# Templates.
#-------------------------------------------------------------------------------
.baseStage:
    script:
      - echo "Running job '${CI_JOB_NAME}' with an empty script."


.onlyOnMergeRequests:
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


.onlyOnTags:
    rules:
      - if: $CI_COMMIT_TAG_MESSAGE



# 
# Stages.
#-------------------------------------------------------------------------------
.buildStage:
    stage: 🛠️ Build
    extends:
      - .baseStage


.testStage:
    stage: 🧪 Test
    extends:
      - .baseStage


.stagingStage:
    stage: 🏗️ Staging
    extends:
      - .baseStage
      - .onlyOnMergeRequests


.testStagingStage:
    stage: 🧪🏗️ Test Staging
    extends:
      - .baseStage
      - .onlyOnMergeRequests


.cleanupStage:
    stage: 🗑️ Clean Up
    extends:
      - .baseStage
      - .onlyOnMergeRequests


.deployStage:
    stage: 🚀 Deploy
    extends:
      - .baseStage
      - .onlyOnTags


.releaseStage:
    stage: 📦 Release
    extends:
      - .baseStage
      - .onlyOnTags