spec:
    inputs:
        deployOn:
            description: Control if deployment jobs should run for tag pipelines or for default branch pipelines.
            options:
              - defaultBranch
              - tag
              - none
            default: none

---

# 
# Workflow
#-------------------------------------------------------------------------------
workflow:
    name: ${pipelineName}
    
    rules:
        # Fix duplicated pipelines on merge requests.
      - if: $CI_PIPELINE_SOURCE == 'push' && $CI_OPEN_MERGE_REQUESTS
        when: never
        
        # Schedules.
      - if: $CI_PIPELINE_SOURCE == 'schedule'
        variables:
            CI_PIPELINE_TYPE: scheduled
            pipelineName: Scheduled Pipeline for Branch '${CI_COMMIT_BRANCH}'
        
        # Branches.
      - if: $CI_COMMIT_BRANCH
        variables:
            CI_PIPELINE_TYPE: branch
            pipelineName: Pipeline for Branch '${CI_COMMIT_BRANCH}'
        
        # Merge requests.
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        variables:
            CI_PIPELINE_TYPE: merge_request
            pipelineName: Pipeline for Merge Request '${CI_MERGE_REQUEST_TITLE}'
        
        # Annotated tags.
      - if: $CI_COMMIT_TAG_MESSAGE
        variables:
            CI_PIPELINE_TYPE: tag
            pipelineName: Release Pipeline for Tag '${CI_COMMIT_TAG}'
        
        # Lightweight tags.
      - if: $CI_COMMIT_TAG
        when: never
        
        # Unknown.
      - variables:
            CI_PIPELINE_TYPE: unknown
            pipelineName: Unknown Pipeline From '${CI_PIPELINE_SOURCE}'



# 
# Stages
#-------------------------------------------------------------------------------
stages:
  - !reference [ .preBuildStage,       stage ]
  - !reference [ .buildStage,          stage ]
  - !reference [ .testStage,           stage ]
  - !reference [ .stagingPrepareStage, stage ]
  - !reference [ .stagingDeployStage,  stage ]
  - !reference [ .stagingTestStage,    stage ]
  - !reference [ .stagingCleanupStage, stage ]
  - !reference [ .prepareStage,        stage ]
  - !reference [ .deployStage,         stage ]
  - !reference [ .releaseStage,        stage ]



# 
# Templates
#-------------------------------------------------------------------------------
variables:
    CI_DEPLOY_ON: $[[ inputs.deployOn ]]


.baseStage:
    script:
      - echo "Running job '${CI_JOB_NAME}' with an empty script."


.rules:
    deployToStaging:
      - if: $CI_PIPELINE_TYPE == 'merge_request'
            
      - if: $CI_PIPELINE_TYPE == 'branch' &&
            $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH &&
            $CI_DEPLOY_ON == 'defaultBranch'
            
      - if: $CI_PIPELINE_TYPE == 'tag' &&
            $CI_DEPLOY_ON == 'tag'
    
    deployToProduction:
      - if: $CI_PIPELINE_TYPE == 'branch' &&
            $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH &&
            $CI_DEPLOY_ON == 'defaultBranch'
            
      - if: $CI_PIPELINE_TYPE == 'tag' &&
            $CI_DEPLOY_ON == 'tag'



# 
# Stages
#-------------------------------------------------------------------------------
.preBuildStage:
    stage: 🛠️ Pre-Build
    
    extends: .baseStage
    
    interruptible: true


.buildStage:
    stage: 🏗️ Build
    
    extends: .baseStage
    
    interruptible: true


.testStage:
    stage: 🧪 Test
    
    extends: .baseStage
    
    interruptible: true


.stagingPrepareStage:
    stage: 🚧 📋 Prepare (Staging)
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToStaging ]


.stagingDeployStage:
    stage: 🚧 🚀 Deploy (Staging)
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToStaging ]


.stagingTestStage:
    stage: 🚧 🧪 Test (Staging)
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToStaging ]


.stagingCleanupStage:
    stage: 🚧 🗑️ Clean Up (Staging)
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToStaging ]


.prepareStage:
    stage: 📋 Prepare
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToProduction ]


.deployStage:
    stage: 🚀 Deploy
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToProduction ]


.releaseStage:
    stage: 📦 Release
    
    extends: .baseStage
    
    rules:
      - !reference [ .rules, deployToProduction ]